<?php

use Illuminate\Database\Seeder;

class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $projects = [
            ["district_id" => 131, "project_code" => "0709501", "project_name" => "Anand Parvat"],
	          ["district_id" => 131, "project_code" => "0709502", "project_name" => "Chandni Chowk"],
	          ["district_id" => 131, "project_code" => "0709503", "project_name" => "Jama Masjid"],
	          ["district_id" => 131, "project_code" => "0709504", "project_name" => "Nabi Karim"],
            ["district_id" => 135, "project_code" => "0709201", "project_name" => "Anand Mansarovar"],
          	["district_id" => 135, "project_code" => "0709202", "project_name" => "Babarpur"],
          	["district_id" => 135, "project_code" => "0709203", "project_name" => "Bhagirathi Vihar"],
          	["district_id" => 135, "project_code" => "0709204", "project_name" => "Gautam Vihar"],
          	["district_id" => 135, "project_code" => "0709205", "project_name" => "Karawal Nagar"],
          	["district_id" => 135, "project_code" => "0709206", "project_name" => "Kardampuri"],
          	["district_id" => 135, "project_code" => "0709207", "project_name" => "Nand Nagri"],
          	["district_id" => 135, "project_code" => "0709208", "project_name" => "Seelam Pur"],
          	["district_id" => 135, "project_code" => "0709209", "project_name" => "Seema Puri"],
          	["district_id" => 135, "project_code" => "0709210", "project_name" => "Shahdara"],
          	["district_id" => 135, "project_code" => "0709211", "project_name" => "Shiv Vihar"],
          	["district_id" => 135, "project_code" => "0709212", "project_name" => "Sonia Vihar"],
          	["district_id" => 135, "project_code" => "0709213", "project_name" => "Sri Ram Colony"],
          	["district_id" => 135, "project_code" => "0709214", "project_name" => "Sunder Nagri"],
          	["district_id" => 135, "project_code" => "0709215", "project_name" => "Wazirabad"],
            ["district_id" => 107, "project_code" => "3362901", "project_name" => "Agastheeswaram"],
          	["district_id" => 107, "project_code" => "3362902", "project_name" => "Killioor"],
          	["district_id" => 107, "project_code" => "3362903", "project_name" => "Kurunthancode"],
          	["district_id" => 107, "project_code" => "3362904", "project_name" => "Melpuram"],
          	["district_id" => 107, "project_code" => "3362905", "project_name" => "Munchirai"],
          	["district_id" => 107, "project_code" => "3362906", "project_name" => "Nagercoil"],
          	["district_id" => 107, "project_code" => "3362907", "project_name" => "Rajakamangalam"],
          	["district_id" => 107, "project_code" => "3362908", "project_name" => "Thiruvattar"],
          	["district_id" => 107, "project_code" => "3362909", "project_name" => "Thovalai"],
          	["district_id" => 107, "project_code" => "3362910", "project_name" => "Thuckalay"],
            ["district_id" => 100, "project_code" => "3360305", "project_name" => "Annanagar"],
          	["district_id" => 100, "project_code" => "3360304", "project_name" => "Ashoknagar"],
          	["district_id" => 100, "project_code" => "3360303", "project_name" => "Chindadripettai"],
          	["district_id" => 100, "project_code" => "3360301", "project_name" => "Kasimedu"],
          	["district_id" => 100, "project_code" => "3360311", "project_name" => "Mylapore"],
          	["district_id" => 100, "project_code" => "3360302", "project_name" => "Nungambakkam"],
          	["district_id" => 100, "project_code" => "3360307", "project_name" => "Perambur"],
          	["district_id" => 100, "project_code" => "3360306", "project_name" => "Puliyanthope"],
          	["district_id" => 100, "project_code" => "3360309", "project_name" => "Royapuram"],
          	["district_id" => 100, "project_code" => "3360310", "project_name" => "Saidapettai"],
          	["district_id" => 100, "project_code" => "3360308", "project_name" => "Thiyagarayanagar"],
          	["district_id" => 100, "project_code" => "3360312", "project_name" => "Vyasarpadi"],
            ["district_id" => 86, "project_code" => "1225901", "project_name" => "TEZU"],
	          ["district_id" => 86, "project_code" => "1225902", "project_name" => "WAKRO"],
            ["district_id" => 80, "project_code" => "1225301", "project_name" => "BORDUMSA-DIYUM"],
          	["district_id" => 80, "project_code" => "1225302", "project_name" => "CHANGLANG"],
          	["district_id" => 80, "project_code" => "1225303", "project_name" => "KHAGAM"],
          	["district_id" => 80, "project_code" => "1225304", "project_name" => "KHIMIYANG"],
          	["district_id" => 80, "project_code" => "1225305", "project_name" => "MANAOW"],
          	["district_id" => 80, "project_code" => "1225306", "project_name" => "NAMPONG"],
            ["district_id" => 63, "project_code" => "0102101", "project_name" => "Akhnoor"],
          	["district_id" => 63, "project_code" => "0102102", "project_name" => "Bishnah"],
          	["district_id" => 63, "project_code" => "0102103", "project_name" => "Dansal"],
          	["district_id" => 63, "project_code" => "0102104", "project_name" => "Gandhi Nagar"],
          	["district_id" => 63, "project_code" => "0102105", "project_name" => "Jammu"],
          	["district_id" => 63, "project_code" => "0102106", "project_name" => "Khour"],
          	["district_id" => 63, "project_code" => "0102107", "project_name" => "Kot Bhalwal"],
          	["district_id" => 63, "project_code" => "0102108", "project_name" => "Marh"],
          	["district_id" => 63, "project_code" => "0102110", "project_name" => "Ranbir Singh Pora"],
          	["district_id" => 63, "project_code" => "0102112", "project_name" => "Satwari"],
            ["district_id" => 69, "project_code" => "0100301", "project_name" => "Durbuk"],
          	["district_id" => 69, "project_code" => "0100302", "project_name" => "Khaltsi"],
          	["district_id" => 69, "project_code" => "0100303", "project_name" => "Kharu"],
          	["district_id" => 69, "project_code" => "0100304", "project_name" => "Leh"],
          	["district_id" => 69, "project_code" => "0100305", "project_name" => "Nobra"],
          	["district_id" => 69, "project_code" => "0100306", "project_name" => "Nyoma"],
            ["district_id" => 36, "project_code" => "2447301", "project_name" => "DEHGAM-1"],
          	["district_id" => 36, "project_code" => "2447302", "project_name" => "DEHGAM-2"],
          	["district_id" => 36, "project_code" => "2447303", "project_name" => "GANDHINAGAR-1"],
          	["district_id" => 36, "project_code" => "2447304", "project_name" => "GANDHINAGAR-2"],
          	["district_id" => 36, "project_code" => "2447305", "project_name" => "KALOL-(G)"],
          	["district_id" => 36, "project_code" => "2447306", "project_name" => "MANSA"],
            ["district_id" => 24, "project_code" => "2447416", "project_name" => "AHMEDABAD CITY"],
          	["district_id" => 24, "project_code" => "2447401", "project_name" => "AHMEDABAD-(U)-01"],
          	["district_id" => 24, "project_code" => "2447402", "project_name" => "AHMEDABAD-(U)-02"],
          	["district_id" => 24, "project_code" => "2447403", "project_name" => "AHMEDABAD-(U)-03"],
          	["district_id" => 24, "project_code" => "2447404", "project_name" => "AHMEDABAD-(U)-04"],
          	["district_id" => 24, "project_code" => "2447405", "project_name" => "AHMEDABAD-(U)-05"],
          	["district_id" => 24, "project_code" => "2447406", "project_name" => "AHMEDABAD-(U)-06"],
          	["district_id" => 24, "project_code" => "2447407", "project_name" => "AHMEDABAD-(U)-07"],
          	["district_id" => 24, "project_code" => "2447408", "project_name" => "AHMEDABAD-(U)-08"],
          	["district_id" => 24, "project_code" => "2447409", "project_name" => "AHMEDABAD-(U)-09"],
          	["district_id" => 24, "project_code" => "2447410", "project_name" => "AHMEDABAD-(U)-10"],
          	["district_id" => 24, "project_code" => "2447412", "project_name" => "Bavla"],
          	["district_id" => 24, "project_code" => "2447413", "project_name" => "DASKOI-1"],
          	["district_id" => 24, "project_code" => "2447414", "project_name" => "DASKOI-2"],
          	["district_id" => 24, "project_code" => "2447415", "project_name" => "DETROJ"],
          	["district_id" => 24, "project_code" => "2447417", "project_name" => "DHANDHUKA"],
          	["district_id" => 24, "project_code" => "2447418", "project_name" => "DHOLKA-1"],
          	["district_id" => 24, "project_code" => "2447419", "project_name" => "DHOLKA-2"],
          	["district_id" => 24, "project_code" => "2447420", "project_name" => "MANDAL"],
          	["district_id" => 24, "project_code" => "2447422", "project_name" => "SANAND"],
          	["district_id" => 24, "project_code" => "2447423", "project_name" => "VIRAMGAM"],
            ["district_id" => 11, "project_code" => "1934101", "project_name" => "Amta - I"],
          	["district_id" => 11, "project_code" => "1934102", "project_name" => "Amta - II"],
          	["district_id" => 11, "project_code" => "1934103", "project_name" => "Bagnan I"],
          	["district_id" => 11, "project_code" => "1934104", "project_name" => "Bagnan II"],
          	["district_id" => 11, "project_code" => "1934105", "project_name" => "Bally (U)"],
          	["district_id" => 11, "project_code" => "1934106", "project_name" => "Bally Jagacha"],
          	["district_id" => 11, "project_code" => "1934107", "project_name" => "Domjur"],
          	["district_id" => 11, "project_code" => "1934108", "project_name" => "Domjur Addl"],
          	["district_id" => 11, "project_code" => "1934109", "project_name" => "Howrah Cenral"],
          	["district_id" => 11, "project_code" => "1934110", "project_name" => "Howrah North"],
          	["district_id" => 11, "project_code" => "1934120", "project_name" => "Jagatballabhpur Addl."],
          	["district_id" => 11, "project_code" => "1934111", "project_name" => "Jagatballavpur"],
          	["district_id" => 11, "project_code" => "1934112", "project_name" => "Panchla"],
          	["district_id" => 11, "project_code" => "1934114", "project_name" => "Sankrail"],
          	["district_id" => 11, "project_code" => "1934113", "project_name" => "Sankrail Addl"],
          	["district_id" => 11, "project_code" => "1934115", "project_name" => "SHIBPUR (U)"],
          	["district_id" => 11, "project_code" => "1934116", "project_name" => "Shyampur I"],
          	["district_id" => 11, "project_code" => "1934117", "project_name" => "Shyampur II"],
          	["district_id" => 11, "project_code" => "1934118", "project_name" => "Udaynarayanpur"],
          	["district_id" => 11, "project_code" => "1934122", "project_name" => "Ulluberia I"],
          	["district_id" => 11, "project_code" => "1934121", "project_name" => "Uluberia (U)"],
          	["district_id" => 11, "project_code" => "1934123", "project_name" => "Uluberia II"],
            ["district_id" => 10, "project_code" => "1933801", "project_name" => "Arambagh"],
          	["district_id" => 10, "project_code" => "1933802", "project_name" => "Arambagh-Addl"],
          	["district_id" => 10, "project_code" => "1933803", "project_name" => "BAIDYABATI"],
          	["district_id" => 10, "project_code" => "1933804", "project_name" => "Balagarh"],
          	["district_id" => 10, "project_code" => "1933805", "project_name" => "Balagarh Addl."],
          	["district_id" => 10, "project_code" => "1933806", "project_name" => "Bansberia Urban"],
          	["district_id" => 10, "project_code" => "1933807", "project_name" => "Bhadreswar"],
          	["district_id" => 10, "project_code" => "1933808", "project_name" => "CHAMPDANI Urban"],
          	["district_id" => 10, "project_code" => "1933809", "project_name" => "Chandannagar"],
          	["district_id" => 10, "project_code" => "1933810", "project_name" => "CHANDITALA-1"],
          	["district_id" => 10, "project_code" => "1933811", "project_name" => "Chanditala-II"],
          	["district_id" => 10, "project_code" => "1933812", "project_name" => "CHINSURA MOGRA"],
          	["district_id" => 10, "project_code" => "1933815", "project_name" => "Chinsurah Mogra Addl."],
          	["district_id" => 10, "project_code" => "1933813", "project_name" => "Dhaniakhali"],
          	["district_id" => 10, "project_code" => "1933814", "project_name" => "Dhaniakhali-Addl"],
          	["district_id" => 10, "project_code" => "1933816", "project_name" => "Goghat 1"],
          	["district_id" => 10, "project_code" => "1933817", "project_name" => "GOGHAT-II"],
          	["district_id" => 10, "project_code" => "1933818", "project_name" => "Haripal"],
          	["district_id" => 10, "project_code" => "1933822", "project_name" => "Haripal Addl."],
          	["district_id" => 10, "project_code" => "1933819", "project_name" => "HOOGHLYCHINSURA Urban"],
          	["district_id" => 10, "project_code" => "1933827", "project_name" => "Jangipara Addl."],
          	["district_id" => 10, "project_code" => "1933820", "project_name" => "Jangipara-Main"],
          	["district_id" => 10, "project_code" => "1933823", "project_name" => "Khanakul I Addl"],
          	["district_id" => 10, "project_code" => "1933821", "project_name" => "Khanakul-I"],
          	["district_id" => 10, "project_code" => "1933824", "project_name" => "Khankul-II"],
          	["district_id" => 10, "project_code" => "1933825", "project_name" => "Pandua"],
          	["district_id" => 10, "project_code" => "1933826", "project_name" => "Pandua Addl"],
          	["district_id" => 10, "project_code" => "1933828", "project_name" => "Polba"],
          	["district_id" => 10, "project_code" => "1933829", "project_name" => "Polba Addl"],
          	["district_id" => 10, "project_code" => "1933830", "project_name" => "Pursurah"],
          	["district_id" => 10, "project_code" => "1933831", "project_name" => "Rishra- Konnagar"],
          	["district_id" => 10, "project_code" => "1933832", "project_name" => "Serampore Urban"],
          	["district_id" => 10, "project_code" => "1933833", "project_name" => "Serampore Uttarpara"],
          	["district_id" => 10, "project_code" => "1933834", "project_name" => "SINGUR"],
          	["district_id" => 10, "project_code" => "1933835", "project_name" => "SINGUR - Addl"],
          	["district_id" => 10, "project_code" => "1933836", "project_name" => "Tarakeswar"],
          	["district_id" => 10, "project_code" => "1933837", "project_name" => "UTTRAPARA- KOTRUNG Urban"],
        ];

        foreach ($projects as $project) {
          DB::table('icds_projects')->insert([
            'district_id' => $project['district_id'],
            'project_code' => $project['project_code'],
            'project_name' => $project['project_name'],
            'created_at' => now(),
            'updated_at' => now(),
          ]);
        }
    }
}
